version: 2

sources:
  - name: public_data
    database: snowflake_public_data_free
    schema: public_data_free
    tables:
      - name: stock_price_timeseries
        description: "Renset aktiekursdata"

      - name: company_index
        description: "Renset oplysninger om aktier og virksomheder"
        columns:
          - name: company_name
            tests:
              - not_null
      - name: fx_rates_timeseries
        description: "Historiske FX rater"


models:
  - name: stg_stock_prices
    description: "Renset tabel med daglige aktiekurser."
    columns:
      - name: stock_price_id
        description: "Primær nøgle (TICKER + DATE)"
        tests:
          - unique
          - not_null
      - name: ticker_symbol
        tests:
          - not_null
      - name: closing_price_usd
        tests:
          - not_null

  - name: stg_fx_rates
    description: "Valutakurser pr. dag."
    columns:
      - name: fx_rate_id
        tests:
          - unique
          - not_null
      - name: rate_to_usd
        tests:
          - not_null
